// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: apps.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getAppBySlug = `-- name: GetAppBySlug :one
SELECT
  e.id, e.uuid, a.slug, a.name, e.created_at, e.updated_at, e.archived_at
FROM apps a
JOIN entities e ON a.id = e.id
WHERE a.slug = $1
`

type GetAppBySlugRow struct {
	ID         int64              `json:"id"`
	Uuid       uuid.UUID          `json:"uuid"`
	Slug       string             `json:"slug"`
	Name       string             `json:"name"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	ArchivedAt *time.Time         `json:"archived_at"`
}

func (q *Queries) GetAppBySlug(ctx context.Context, slug string) (GetAppBySlugRow, error) {
	row := q.db.QueryRow(ctx, getAppBySlug, slug)
	var i GetAppBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Slug,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const getAppByUUID = `-- name: GetAppByUUID :one
SELECT
  e.id, e.uuid, a.slug, a.name, e.created_at, e.updated_at, e.archived_at
FROM apps a
JOIN entities e ON a.id = e.id
WHERE e.uuid = $1
`

type GetAppByUUIDRow struct {
	ID         int64              `json:"id"`
	Uuid       uuid.UUID          `json:"uuid"`
	Slug       string             `json:"slug"`
	Name       string             `json:"name"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	ArchivedAt *time.Time         `json:"archived_at"`
}

func (q *Queries) GetAppByUUID(ctx context.Context, argUuid uuid.UUID) (GetAppByUUIDRow, error) {
	row := q.db.QueryRow(ctx, getAppByUUID, argUuid)
	var i GetAppByUUIDRow
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Slug,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const insertApp = `-- name: InsertApp :one

INSERT INTO apps (id, slug, name)
VALUES ($1, $2, $3)
RETURNING id, slug, name
`

type InsertAppParams struct {
	ID   int64  `json:"id"`
	Slug string `json:"slug"`
	Name string `json:"name"`
}

// Entity creation (fundamental_type = 'app') and archival reuse the existing
// generic entities.sql queries (GetTypeBySlug + CreateEntity to create,
// ArchiveEntity to archive) — the same pattern every other entity subtype
// (corporation, natural_person, service_account) already follows. Only the
// apps-table-specific operations are defined here.
func (q *Queries) InsertApp(ctx context.Context, arg InsertAppParams) (App, error) {
	row := q.db.QueryRow(ctx, insertApp, arg.ID, arg.Slug, arg.Name)
	var i App
	err := row.Scan(&i.ID, &i.Slug, &i.Name)
	return i, err
}

const listApps = `-- name: ListApps :many
SELECT
  e.id, e.uuid, a.slug, a.name, e.created_at, e.updated_at, e.archived_at
FROM apps a
JOIN entities e ON a.id = e.id
WHERE e.archived_at IS NULL
ORDER BY a.name
`

type ListAppsRow struct {
	ID         int64              `json:"id"`
	Uuid       uuid.UUID          `json:"uuid"`
	Slug       string             `json:"slug"`
	Name       string             `json:"name"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	ArchivedAt *time.Time         `json:"archived_at"`
}

func (q *Queries) ListApps(ctx context.Context) ([]ListAppsRow, error) {
	rows, err := q.db.Query(ctx, listApps)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAppsRow
	for rows.Next() {
		var i ListAppsRow
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Slug,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateApp = `-- name: UpdateApp :exec
UPDATE apps
SET slug = $2, name = $3
WHERE id = $1
`

type UpdateAppParams struct {
	ID   int64  `json:"id"`
	Slug string `json:"slug"`
	Name string `json:"name"`
}

func (q *Queries) UpdateApp(ctx context.Context, arg UpdateAppParams) error {
	_, err := q.db.Exec(ctx, updateApp, arg.ID, arg.Slug, arg.Name)
	return err
}
