// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: corporations.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCorporation = `-- name: CreateCorporation :one
INSERT INTO corporations (entity_id, legal_name, jurisdiction, ein)
VALUES ($1, $2, $3, $4)
RETURNING id, entity_id, legal_name, jurisdiction, created_at, updated_at, ein
`

type CreateCorporationParams struct {
	EntityID     int64       `json:"entity_id"`
	LegalName    string      `json:"legal_name"`
	Jurisdiction pgtype.Text `json:"jurisdiction"`
	Ein          []byte      `json:"ein"`
}

type CreateCorporationRow struct {
	ID           int64              `json:"id"`
	EntityID     int64              `json:"entity_id"`
	LegalName    string             `json:"legal_name"`
	Jurisdiction pgtype.Text        `json:"jurisdiction"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	Ein          []byte             `json:"ein"`
}

func (q *Queries) CreateCorporation(ctx context.Context, arg CreateCorporationParams) (CreateCorporationRow, error) {
	row := q.db.QueryRow(ctx, createCorporation,
		arg.EntityID,
		arg.LegalName,
		arg.Jurisdiction,
		arg.Ein,
	)
	var i CreateCorporationRow
	err := row.Scan(
		&i.ID,
		&i.EntityID,
		&i.LegalName,
		&i.Jurisdiction,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Ein,
	)
	return i, err
}

const getCorporationByEntityID = `-- name: GetCorporationByEntityID :one
SELECT id, entity_id, legal_name, jurisdiction, created_at, updated_at, ein
FROM corporations
WHERE entity_id = $1
`

type GetCorporationByEntityIDRow struct {
	ID           int64              `json:"id"`
	EntityID     int64              `json:"entity_id"`
	LegalName    string             `json:"legal_name"`
	Jurisdiction pgtype.Text        `json:"jurisdiction"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	Ein          []byte             `json:"ein"`
}

func (q *Queries) GetCorporationByEntityID(ctx context.Context, entityID int64) (GetCorporationByEntityIDRow, error) {
	row := q.db.QueryRow(ctx, getCorporationByEntityID, entityID)
	var i GetCorporationByEntityIDRow
	err := row.Scan(
		&i.ID,
		&i.EntityID,
		&i.LegalName,
		&i.Jurisdiction,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Ein,
	)
	return i, err
}

const updateCorporation = `-- name: UpdateCorporation :exec
UPDATE corporations
SET legal_name = $2,
    jurisdiction = $3,
    ein = COALESCE($4, ein)
WHERE entity_id = $1
`

type UpdateCorporationParams struct {
	EntityID     int64       `json:"entity_id"`
	LegalName    string      `json:"legal_name"`
	Jurisdiction pgtype.Text `json:"jurisdiction"`
	Ein          []byte      `json:"ein"`
}

// NOTE: pass NULL for ein to leave it unchanged; pass an empty bytea
// to clear it. A non-empty bytea replaces it.
func (q *Queries) UpdateCorporation(ctx context.Context, arg UpdateCorporationParams) error {
	_, err := q.db.Exec(ctx, updateCorporation,
		arg.EntityID,
		arg.LegalName,
		arg.Jurisdiction,
		arg.Ein,
	)
	return err
}

const updateCorporationEINBlob = `-- name: UpdateCorporationEINBlob :execrows
UPDATE corporations
SET ein = $1
WHERE entity_id = $2 AND ein = $3
`

type UpdateCorporationEINBlobParams struct {
	NewEin   []byte `json:"new_ein"`
	EntityID int64  `json:"entity_id"`
	OldEin   []byte `json:"old_ein"`
}

// Re-encrypt-on-read write-back: replaces the stored ein blob with a
// freshly re-encrypted one. The old-ein predicate is a compare-and-swap
// guard, not a lookup condition: it ensures the write only lands if the
// stored blob is still the one that was read, so a concurrent writer's
// change is never clobbered.
func (q *Queries) UpdateCorporationEINBlob(ctx context.Context, arg UpdateCorporationEINBlobParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateCorporationEINBlob, arg.NewEin, arg.EntityID, arg.OldEin)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
