// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: entities.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const archiveEntity = `-- name: ArchiveEntity :exec
UPDATE entities
SET archived_at = now()
WHERE uuid = $1 AND archived_at IS NULL
`

func (q *Queries) ArchiveEntity(ctx context.Context, argUuid uuid.UUID) error {
	_, err := q.db.Exec(ctx, archiveEntity, argUuid)
	return err
}

const createEntity = `-- name: CreateEntity :one
INSERT INTO entities (fundamental_type_id)
VALUES ($1)
RETURNING id, uuid, fundamental_type_id, created_at, updated_at, archived_at, owner_id
`

func (q *Queries) CreateEntity(ctx context.Context, fundamentalTypeID int64) (Entity, error) {
	row := q.db.QueryRow(ctx, createEntity, fundamentalTypeID)
	var i Entity
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.FundamentalTypeID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
		&i.OwnerID,
	)
	return i, err
}

const getEntityByID = `-- name: GetEntityByID :one
SELECT
  e.id, e.uuid, e.fundamental_type_id,
  t.slug AS fundamental_type_slug,
  e.created_at, e.updated_at, e.archived_at
FROM entities e
JOIN types t ON e.fundamental_type_id = t.id
WHERE e.id = $1
`

type GetEntityByIDRow struct {
	ID                  int64              `json:"id"`
	Uuid                uuid.UUID          `json:"uuid"`
	FundamentalTypeID   int64              `json:"fundamental_type_id"`
	FundamentalTypeSlug string             `json:"fundamental_type_slug"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	ArchivedAt          *time.Time         `json:"archived_at"`
}

func (q *Queries) GetEntityByID(ctx context.Context, id int64) (GetEntityByIDRow, error) {
	row := q.db.QueryRow(ctx, getEntityByID, id)
	var i GetEntityByIDRow
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.FundamentalTypeID,
		&i.FundamentalTypeSlug,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const getEntityByUUID = `-- name: GetEntityByUUID :one
SELECT
  e.id, e.uuid, e.fundamental_type_id,
  t.slug AS fundamental_type_slug,
  e.created_at, e.updated_at, e.archived_at
FROM entities e
JOIN types t ON e.fundamental_type_id = t.id
WHERE e.uuid = $1
`

type GetEntityByUUIDRow struct {
	ID                  int64              `json:"id"`
	Uuid                uuid.UUID          `json:"uuid"`
	FundamentalTypeID   int64              `json:"fundamental_type_id"`
	FundamentalTypeSlug string             `json:"fundamental_type_slug"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	ArchivedAt          *time.Time         `json:"archived_at"`
}

func (q *Queries) GetEntityByUUID(ctx context.Context, argUuid uuid.UUID) (GetEntityByUUIDRow, error) {
	row := q.db.QueryRow(ctx, getEntityByUUID, argUuid)
	var i GetEntityByUUIDRow
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.FundamentalTypeID,
		&i.FundamentalTypeSlug,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const unarchiveEntity = `-- name: UnarchiveEntity :exec
UPDATE entities
SET archived_at = NULL
WHERE uuid = $1 AND archived_at IS NOT NULL
`

func (q *Queries) UnarchiveEntity(ctx context.Context, argUuid uuid.UUID) error {
	_, err := q.db.Exec(ctx, unarchiveEntity, argUuid)
	return err
}
