// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: field_crypto_keys.sql

package db

import (
	"context"
)

const getFieldCryptoKey = `-- name: GetFieldCryptoKey :one
SELECT key_bytes FROM field_crypto_keys WHERE id = 1
`

func (q *Queries) GetFieldCryptoKey(ctx context.Context) ([]byte, error) {
	row := q.db.QueryRow(ctx, getFieldCryptoKey)
	var key_bytes []byte
	err := row.Scan(&key_bytes)
	return key_bytes, err
}

const insertFieldCryptoKeyIfAbsent = `-- name: InsertFieldCryptoKeyIfAbsent :one
INSERT INTO field_crypto_keys (id, key_bytes)
VALUES (1, $1)
ON CONFLICT (id) DO NOTHING
RETURNING key_bytes
`

func (q *Queries) InsertFieldCryptoKeyIfAbsent(ctx context.Context, keyBytes []byte) ([]byte, error) {
	row := q.db.QueryRow(ctx, insertFieldCryptoKeyIfAbsent, keyBytes)
	var key_bytes []byte
	err := row.Scan(&key_bytes)
	return key_bytes, err
}
