// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: legal_entities.sql

package db

import (
	"context"
)

const createLegalEntity = `-- name: CreateLegalEntity :one
INSERT INTO legal_entities (entity_id)
VALUES ($1)
RETURNING entity_id
`

func (q *Queries) CreateLegalEntity(ctx context.Context, entityID int64) (int64, error) {
	row := q.db.QueryRow(ctx, createLegalEntity, entityID)
	var entity_id int64
	err := row.Scan(&entity_id)
	return entity_id, err
}

const getLegalEntityByEntityID = `-- name: GetLegalEntityByEntityID :one
SELECT entity_id
FROM legal_entities
WHERE entity_id = $1
`

func (q *Queries) GetLegalEntityByEntityID(ctx context.Context, entityID int64) (int64, error) {
	row := q.db.QueryRow(ctx, getLegalEntityByEntityID, entityID)
	var entity_id int64
	err := row.Scan(&entity_id)
	return entity_id, err
}
