// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Corporation struct {
	ID            int64              `json:"id"`
	LegalEntityID int64              `json:"legal_entity_id"`
	LegalName     string             `json:"legal_name"`
	Jurisdiction  pgtype.Text        `json:"jurisdiction"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type Entity struct {
	ID         int64              `json:"id"`
	Uuid       uuid.UUID          `json:"uuid"`
	Kind       string             `json:"kind"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	ArchivedAt *time.Time         `json:"archived_at"`
}

type LegalEntity struct {
	ID          int64              `json:"id"`
	EntityID    int64              `json:"entity_id"`
	Kind        string             `json:"kind"`
	DisplayName string             `json:"display_name"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type NaturalPerson struct {
	ID            int64              `json:"id"`
	LegalEntityID int64              `json:"legal_entity_id"`
	GivenName     pgtype.Text        `json:"given_name"`
	FamilyName    pgtype.Text        `json:"family_name"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type ServiceAccount struct {
	ID        int64              `json:"id"`
	EntityID  int64              `json:"entity_id"`
	Label     string             `json:"label"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
