// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	ArchiveEntity(ctx context.Context, argUuid uuid.UUID) error
	CreateCorporation(ctx context.Context, arg CreateCorporationParams) (Corporation, error)
	CreateEntity(ctx context.Context, kind string) (Entity, error)
	CreateLegalEntity(ctx context.Context, arg CreateLegalEntityParams) (LegalEntity, error)
	CreateNaturalPerson(ctx context.Context, arg CreateNaturalPersonParams) (NaturalPerson, error)
	CreateServiceAccount(ctx context.Context, arg CreateServiceAccountParams) (ServiceAccount, error)
	GetCorporationByLegalEntityID(ctx context.Context, legalEntityID int64) (Corporation, error)
	GetEntityByUUID(ctx context.Context, argUuid uuid.UUID) (Entity, error)
	GetLegalEntityByEntityID(ctx context.Context, entityID int64) (LegalEntity, error)
	GetNaturalPersonByLegalEntityID(ctx context.Context, legalEntityID int64) (NaturalPerson, error)
	GetServiceAccountByEntityID(ctx context.Context, entityID int64) (ServiceAccount, error)
	UnarchiveEntity(ctx context.Context, argUuid uuid.UUID) error
	UpdateCorporation(ctx context.Context, arg UpdateCorporationParams) error
	UpdateNaturalPerson(ctx context.Context, arg UpdateNaturalPersonParams) error
}

var _ Querier = (*Queries)(nil)
