// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: types.sql

package db

import (
	"context"
)

const getTypeByID = `-- name: GetTypeByID :one
SELECT id, slug, parent_id, concrete, name, description, created_at, deprecated_at
FROM types
WHERE id = $1
`

func (q *Queries) GetTypeByID(ctx context.Context, id int64) (Type, error) {
	row := q.db.QueryRow(ctx, getTypeByID, id)
	var i Type
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.ParentID,
		&i.Concrete,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.DeprecatedAt,
	)
	return i, err
}

const getTypeBySlug = `-- name: GetTypeBySlug :one
SELECT id, slug, parent_id, concrete, name, description, created_at, deprecated_at
FROM types
WHERE slug = $1
`

func (q *Queries) GetTypeBySlug(ctx context.Context, slug string) (Type, error) {
	row := q.db.QueryRow(ctx, getTypeBySlug, slug)
	var i Type
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.ParentID,
		&i.Concrete,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.DeprecatedAt,
	)
	return i, err
}
