package service

import (
	"context"
	"fmt"
	"strings"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"

	"github.com/moduleforge/core-api/audit"
	coredb "github.com/moduleforge/core-model/db"
)

// CreateServiceAccountInput carries the fields required to create a service account.
type CreateServiceAccountInput struct {
	Label string
}

// UpdateServiceAccountInput carries the fields that may be updated on a service account.
// Nil fields are left unchanged.
type UpdateServiceAccountInput struct {
	Label *string
}

// ServiceAccountServicer defines service account operations available to httpapi handlers.
type ServiceAccountServicer interface {
	Create(ctx context.Context, q coredb.Querier, actor Principal, in CreateServiceAccountInput) (coredb.ServiceAccount, uuid.UUID, error)
	GetByEntityUUID(ctx context.Context, q coredb.Querier, entityUUID uuid.UUID) (Profile, error)
	UpdateByEntityUUID(ctx context.Context, q coredb.Querier, entityUUID uuid.UUID, in UpdateServiceAccountInput, actor Principal) error
}

// ServiceAccountService implements service account CRUD with audit logging.
type ServiceAccountService struct {
	aw audit.Writer
}

// Compile-time assertion.
var _ ServiceAccountServicer = (*ServiceAccountService)(nil)

// Create inserts entity → service_account rows in sequence.
// Requires actor.IsAdmin. Note that service accounts do not have a legal_entity
// row — they attach directly to entity.
func (s *ServiceAccountService) Create(
	ctx context.Context,
	q coredb.Querier,
	actor Principal,
	in CreateServiceAccountInput,
) (coredb.ServiceAccount, uuid.UUID, error) {
	if !actor.IsAdmin {
		return coredb.ServiceAccount{}, uuid.UUID{}, ErrForbidden
	}

	in.Label = strings.TrimSpace(in.Label)
	if in.Label == "" {
		return coredb.ServiceAccount{}, uuid.UUID{}, fmt.Errorf("%w: label is required", ErrInvalidInput)
	}

	entity, err := q.CreateEntity(ctx, "service_account")
	if err != nil {
		return coredb.ServiceAccount{}, uuid.UUID{}, fmt.Errorf("service_account.Create entity: %w", err)
	}

	sa, err := q.CreateServiceAccount(ctx, coredb.CreateServiceAccountParams{
		EntityID: entity.ID,
		Label:    in.Label,
	})
	if err != nil {
		return coredb.ServiceAccount{}, uuid.UUID{}, fmt.Errorf("service_account.Create service_account: %w", err)
	}

	eid := entity.ID
	_ = s.aw.Write(ctx, "create", "service_account", &eid, nil, map[string]any{
		"uuid":  entity.Uuid.String(),
		"label": in.Label,
	})

	return sa, entity.Uuid, nil
}

// GetByEntityUUID resolves the entity by UUID and returns its full Profile.
// Requires actor.IsAdmin (callers should check before calling).
func (s *ServiceAccountService) GetByEntityUUID(ctx context.Context, q coredb.Querier, entityUUID uuid.UUID) (Profile, error) {
	entity, err := q.GetEntityByUUID(ctx, entityUUID)
	if err != nil {
		if err == pgx.ErrNoRows {
			return Profile{}, ErrNotFound
		}
		return Profile{}, fmt.Errorf("service_account.GetByEntityUUID entity: %w", err)
	}

	profile, err := ResolveProfileByEntityID(ctx, q, entity.ID)
	if err != nil {
		return Profile{}, fmt.Errorf("service_account.GetByEntityUUID profile: %w", err)
	}
	profile.Entity = entity
	return profile, nil
}

// UpdateByEntityUUID updates service_account fields for the given entity UUID.
// Requires actor.IsAdmin. Since there is no sqlc-emitted UpdateServiceAccount
// query, this performs a raw update by re-inserting the label via available
// interface. In practice the sqlc schema may need an UpdateServiceAccount query
// added; for now we return ErrInvalidInput to signal the operation is not yet
// implemented at the DB layer, preserving a clean interface for consumers.
func (s *ServiceAccountService) UpdateByEntityUUID(
	ctx context.Context,
	q coredb.Querier,
	entityUUID uuid.UUID,
	in UpdateServiceAccountInput,
	actor Principal,
) error {
	if !actor.IsAdmin {
		return ErrForbidden
	}

	if in.Label == nil {
		// Nothing to update.
		return nil
	}

	entity, err := q.GetEntityByUUID(ctx, entityUUID)
	if err != nil {
		if err == pgx.ErrNoRows {
			return ErrNotFound
		}
		return fmt.Errorf("service_account.UpdateByEntityUUID entity: %w", err)
	}

	sa, err := q.GetServiceAccountByEntityID(ctx, entity.ID)
	if err != nil {
		if err == pgx.ErrNoRows {
			return ErrNotFound
		}
		return fmt.Errorf("service_account.UpdateByEntityUUID service_account: %w", err)
	}

	before := map[string]any{"label": sa.Label}

	// UpdateServiceAccount is not in the generated Querier interface.
	// Signal that the update is unsupported until the query is added to sqlc.
	// Returning ErrInvalidInput here is intentional: the interface is defined
	// and the handler wired up, but the DB mutation isn't available yet.
	_ = before
	_ = entity
	return fmt.Errorf("%w: UpdateServiceAccount query not yet generated by sqlc", ErrInvalidInput)
}
