// Package entity defines the Entity interface and thin service-layer types for
// each concrete entity kind in core-module.
//
// These types are not DB row structs (those live in core-model/db and are
// generated by sqlc). Instead they are the service-layer representation that
// carries exactly the information needed to satisfy the Entity contract: the
// stable resource slug, the internal entity ID, and the public UUID.
//
// Observers consume the resource slug; logging and external display use the
// public UUID. The internal entity ID is for joins and FKs only — never for
// public display, log entries, or persistence outside core's own internal
// data layer.
package entity

// Entity is the common interface implemented by every concrete entity kind.
// It is consumed by observers (resource string + entity ID) and by service-
// layer code that needs to log or externally reference an entity by its
// public UUID.
//
// The Authorizer interface does NOT consume Entity — it takes only an *int64
// target ID. Service code calls Entity.EntityID() to obtain that ID when
// invoking Authorize.
type Entity interface {
	// Resource returns the stable, snake_case singular resource name for this
	// entity kind. Examples: "natural_person", "corporation", "service_account".
	// The value is fixed per concrete type and corresponds to the
	// fundamental_type_slug used in the entity-typing registry.
	Resource() string

	// EntityID returns the internal (integer) entity ID. Nil for not-yet-
	// persisted entities (the create case where no DB-assigned ID exists yet).
	//
	// This value must never be publicly displayed, logged, or persisted
	// outside core's internal data layer. Admins may specifically request
	// the ID via dedicated endpoints. Use PublicUUID for any external
	// reference.
	EntityID() *int64

	// PublicUUID returns the public UUID of the entity. This is the canonical
	// external reference for display, logging, and any persisted reference
	// outside the entity's own table. Returns "" for not-yet-persisted
	// entities.
	PublicUUID() string
}

// LegalEntity is the service-layer representation of a legal_entity row.
// Both NaturalPerson and Corporation embed a LegalEntity via the DB hierarchy,
// but LegalEntity may also be used directly when only the legal-entity level
// is known.
type LegalEntity struct {
	// ID is the internal entity ID. Nil when the entity has not yet been
	// persisted (pre-create).
	ID *int64
	// UUID is the public UUID. Empty for not-yet-persisted entities.
	UUID string
}

// Resource implements Entity.
func (e LegalEntity) Resource() string { return "legal_entity" }

// EntityID implements Entity.
func (e LegalEntity) EntityID() *int64 { return e.ID }

// PublicUUID implements Entity.
func (e LegalEntity) PublicUUID() string { return e.UUID }

// NaturalPerson is the service-layer representation of a natural_person entity.
type NaturalPerson struct {
	// ID is the internal entity ID. Nil when the entity has not yet been
	// persisted (pre-create).
	ID *int64
	// UUID is the public UUID. Empty for not-yet-persisted entities.
	UUID string
}

// Resource implements Entity.
func (e NaturalPerson) Resource() string { return "natural_person" }

// EntityID implements Entity.
func (e NaturalPerson) EntityID() *int64 { return e.ID }

// PublicUUID implements Entity.
func (e NaturalPerson) PublicUUID() string { return e.UUID }

// Corporation is the service-layer representation of a corporation entity.
type Corporation struct {
	// ID is the internal entity ID. Nil when the entity has not yet been
	// persisted (pre-create).
	ID *int64
	// UUID is the public UUID. Empty for not-yet-persisted entities.
	UUID string
}

// Resource implements Entity.
func (e Corporation) Resource() string { return "corporation" }

// EntityID implements Entity.
func (e Corporation) EntityID() *int64 { return e.ID }

// PublicUUID implements Entity.
func (e Corporation) PublicUUID() string { return e.UUID }

// ServiceAccount is the service-layer representation of a service_account
// entity. Note that service accounts do not have a legal_entity row; they
// attach directly to the entity table.
type ServiceAccount struct {
	// ID is the internal entity ID. Nil when the entity has not yet been
	// persisted (pre-create).
	ID *int64
	// UUID is the public UUID. Empty for not-yet-persisted entities.
	UUID string
}

// Resource implements Entity.
func (e ServiceAccount) Resource() string { return "service_account" }

// EntityID implements Entity.
func (e ServiceAccount) EntityID() *int64 { return e.ID }

// PublicUUID implements Entity.
func (e ServiceAccount) PublicUUID() string { return e.UUID }
