// Package entity defines the Entity interface and thin service-layer types for
// each concrete entity kind in core-module.
//
// These types are not DB row structs (those live in core-model/db and are
// generated by sqlc). Instead they are the service-layer representation that
// carries exactly the information needed to satisfy the Entity contract:
// a stable resource slug and an internal entity ID.
//
// Observers and the authorizer accept Entity so they can route behaviour by
// resource name and target ID without inspecting concrete types or importing
// module-specific packages.
package entity

// Entity is the common interface implemented by every concrete entity kind.
// It is used by the authorizer (pre-op) and observers (in-tx and post-commit)
// to identify entity types and target IDs without type-asserting.
type Entity interface {
	// Resource returns the stable, snake_case singular resource name for this
	// entity kind. Examples: "natural_person", "corporation", "service_account".
	// The value is fixed per concrete type and corresponds to the
	// fundamental_type_slug used in the entity-typing registry.
	Resource() string

	// EntityID returns the internal (integer) entity ID. It is nil only in
	// the narrow pre-create case where the entity has not yet been persisted
	// and therefore has no DB-assigned ID.
	EntityID() *int64
}

// LegalEntity is the service-layer representation of a legal_entity row.
// Both NaturalPerson and Corporation embed a LegalEntity via the DB hierarchy,
// but LegalEntity may also be used directly when only the legal-entity level
// is known (e.g. an authorizer stub for a not-yet-typed create operation).
type LegalEntity struct {
	// ID is the internal entity ID. Nil when the entity has not yet been
	// persisted (pre-create).
	ID *int64
}

// Resource implements Entity.
func (e LegalEntity) Resource() string { return "legal_entity" }

// EntityID implements Entity.
func (e LegalEntity) EntityID() *int64 { return e.ID }

// NaturalPerson is the service-layer representation of a natural_person entity.
type NaturalPerson struct {
	// ID is the internal entity ID. Nil when the entity has not yet been
	// persisted (pre-create).
	ID *int64
}

// Resource implements Entity.
func (e NaturalPerson) Resource() string { return "natural_person" }

// EntityID implements Entity.
func (e NaturalPerson) EntityID() *int64 { return e.ID }

// Corporation is the service-layer representation of a corporation entity.
type Corporation struct {
	// ID is the internal entity ID. Nil when the entity has not yet been
	// persisted (pre-create).
	ID *int64
}

// Resource implements Entity.
func (e Corporation) Resource() string { return "corporation" }

// EntityID implements Entity.
func (e Corporation) EntityID() *int64 { return e.ID }

// ServiceAccount is the service-layer representation of a service_account entity.
// Note that service accounts do not have a legal_entity row; they attach
// directly to the entity table.
type ServiceAccount struct {
	// ID is the internal entity ID. Nil when the entity has not yet been
	// persisted (pre-create).
	ID *int64
}

// Resource implements Entity.
func (e ServiceAccount) Resource() string { return "service_account" }

// EntityID implements Entity.
func (e ServiceAccount) EntityID() *int64 { return e.ID }
